# hmpc containerfile

# indicates what packages to install in the container image
# packages_for=default (default packages for building)
# packages_for=mpspdz (more packages to also build MP-SPDZ)
ARG packages_for=mpspdz

# base container image
FROM intel/oneapi-runtime@sha256:060ba4aa60a58add8d1d39fd49cd7b3bf274dde0f8ea4a988fdf6eb57abab97e AS base-ubuntu

# container image to build LLVM/dpcpp from source
FROM base-ubuntu AS dpcpp-builder
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y --no-install-recommends \
    git \
    build-essential cmake ninja-build \
    python3-pip \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /workspaces/dpcpp
ARG configure_env=""
ARG configure_features="--native_cpu --llvm-external-projects=clang-tools-extra,compiler-rt,openmp"
ARG compile_parallelism=""
ENV CONFIGURE_ENV=${configure_env}
ENV CONFIGURE_FEATURES=${configure_features}
ENV COMPILE_PARALLELISM=${compile_parallelism}
RUN git clone https://github.com/intel/llvm --branch nightly-2025-01-02 --depth=1 \
 && env ${CONFIGURE_ENV} python3 /workspaces/dpcpp/llvm/buildbot/configure.py ${CONFIGURE_FEATURES} \
 && python3 /workspaces/dpcpp/llvm/buildbot/compile.py ${COMPILE_PARALLELISM} \
 && python3 /workspaces/dpcpp/llvm/buildbot/compile.py --build-target=clang-tidy ${COMPILE_PARALLELISM} \
 && python3 /workspaces/dpcpp/llvm/buildbot/compile.py --build-target=omp ${COMPILE_PARALLELISM} \
 && python3 /workspaces/dpcpp/llvm/buildbot/compile.py --build-target=install ${COMPILE_PARALLELISM}

# base development container image
FROM base-ubuntu AS dev-base
ARG user_id=1000
ARG group_id=1000
ENV CMAKE_ROOT=/opt/cmake
ENV LLVM_ROOT=/opt/dpcpp
ENV VCPKG_ROOT=/workspaces/vcpkg
ENV VCPKG_DISABLE_METRICS=1
ENV PATH=$LLVM_ROOT/bin:$CMAKE_ROOT/bin:/home/hmpc-dev/.cargo/bin:$PATH
ENV LD_LIBRARY_PATH=$LLVM_ROOT/lib/x86_64-unknown-linux-gnu:$LLVM_ROOT/lib:$LD_LIBRARY_PATH
ENV CPATH=$LLVM_ROOT/include:$LLVM_ROOT/include/sycl:$CPATH
COPY --from=dpcpp-builder /workspaces/dpcpp/llvm/build/install/ $LLVM_ROOT
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y --no-install-recommends \
    curl zip unzip tar git \
    build-essential ninja-build \
    python3-pip \
    iproute2 iputils-ping \
    && rm -rf /var/lib/apt/lists/* \
 && groupadd -g ${group_id:?} --non-unique hmpc-dev \
 && useradd --create-home -u ${user_id:?} -g ${group_id:?} --shell /bin/bash hmpc-dev \
 && mkdir -p $CMAKE_ROOT \
 && cd $CMAKE_ROOT \
 && curl -sSfLO https://github.com/Kitware/CMake/releases/download/v3.31.5/cmake-3.31.5-linux-x86_64.sh \
 && sh ./cmake-3.31.5-linux-x86_64.sh --skip-license --prefix=/opt/cmake \
 && rm ./cmake-3.31.5-linux-x86_64.sh
USER hmpc-dev
WORKDIR /workspaces

# default development container image
FROM dev-base AS dev-default
# Recommended way to install Rust: https://www.rust-lang.org/tools/install
RUN --mount=type=bind,source=requirements.txt,target=/home/hmpc-dev/requirements.txt \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
 && rustup toolchain install nightly \
 && cargo install \
    cbindgen@0.28.0 \
 && cd /workspaces \
 && git clone https://github.com/microsoft/vcpkg --depth=1 \
 && $VCPKG_ROOT/bootstrap-vcpkg.sh -disableMetrics \
 && pip3 install -r $HOME/requirements.txt --no-warn-script-location
WORKDIR /workspaces/hmpc

# development container image with extra packages for MP-SPDZ
FROM dev-default AS dev-mpspdz
USER root
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get install -y --no-install-recommends \
    libboost-dev libboost-filesystem-dev libboost-thread-dev \
    libgmp-dev \
    libntl-dev \
    libsodium-dev \
    libssl-dev \
 && rm -rf /var/lib/apt/lists/*
USER hmpc-dev

# container image to build hmpc
FROM dev-default AS hmpc-builder
RUN --mount=type=bind,source=.,target=/workspaces/hmpc \
    cmake --preset default -B /home/hmpc-dev/build -DHMPC_BUILD_TESTING=OFF -DHMPC_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/home/hmpc-dev/install \
 && cmake --build /home/hmpc-dev/build --target install

# hmpc container image (to use hmpc as a dependency)
FROM dev-base AS development
COPY --from=hmpc-builder /home/hmpc-dev/install /usr/local

# hmpc-dev container image (to develop hmpc)
FROM dev-${packages_for} AS library-development
