unstable_features = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

imports_layout = "Horizontal"
imports_granularity = "Module"
group_imports = "StdExternalCrate"

blank_lines_upper_bound = 2
tab_spaces = 4

max_width = 999
chain_width = 80
wrap_comments = false

match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true

use_field_init_shorthand = true
